//! Common types used across Tamandua GUI and core library.
//!
//! These types are shared between the agent, GUI, and backend.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ============================================================================
// Alert Types
// ============================================================================

/// Severity level of an alert
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AlertSeverity {
    /// Critical severity - immediate action required
    Critical,
    /// High severity - action required soon
    High,
    /// Medium severity - should be investigated
    Medium,
    /// Low severity - informational
    Low,
    /// Informational - no action required
    Info,
}

impl Default for AlertSeverity {
    fn default() -> Self {
        Self::Info
    }
}

/// Status of an alert
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AlertStatus {
    /// New alert, not yet reviewed
    New,
    /// Alert is being investigated
    Investigating,
    /// Alert has been resolved
    Resolved,
    /// Alert was a false positive
    FalsePositive,
    /// Alert has been dismissed
    Dismissed,
}

impl Default for AlertStatus {
    fn default() -> Self {
        Self::New
    }
}

/// An alert generated by the detection engine
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    /// Unique alert ID
    pub id: Uuid,
    /// Alert title
    pub title: String,
    /// Alert description
    pub description: String,
    /// Severity level
    pub severity: AlertSeverity,
    /// Current status
    pub status: AlertStatus,
    /// Source of the alert (e.g., "YARA", "Sigma", "ML")
    pub source: String,
    /// MITRE ATT&CK technique IDs
    pub mitre_techniques: Vec<String>,
    /// Affected process ID (if applicable)
    pub process_id: Option<u32>,
    /// Affected file path (if applicable)
    pub file_path: Option<String>,
    /// Agent ID that generated the alert
    pub agent_id: String,
    /// Timestamp when alert was created
    pub created_at: DateTime<Utc>,
    /// Timestamp when alert was last updated
    pub updated_at: DateTime<Utc>,
    /// Additional metadata
    pub metadata: serde_json::Value,
}

impl Alert {
    /// Create a new alert
    pub fn new(
        title: impl Into<String>,
        description: impl Into<String>,
        severity: AlertSeverity,
    ) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            title: title.into(),
            description: description.into(),
            severity,
            status: AlertStatus::New,
            source: String::new(),
            mitre_techniques: Vec::new(),
            process_id: None,
            file_path: None,
            agent_id: String::new(),
            created_at: now,
            updated_at: now,
            metadata: serde_json::Value::Null,
        }
    }
}

/// Filter criteria for querying alerts
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AlertFilter {
    /// Filter by severity levels
    pub severities: Option<Vec<AlertSeverity>>,
    /// Filter by status
    pub statuses: Option<Vec<AlertStatus>>,
    /// Filter by source
    pub sources: Option<Vec<String>>,
    /// Filter by agent ID
    pub agent_id: Option<String>,
    /// Filter by date range start
    pub from_date: Option<DateTime<Utc>>,
    /// Filter by date range end
    pub to_date: Option<DateTime<Utc>>,
    /// Search in title/description
    pub search: Option<String>,
    /// Maximum number of results
    pub limit: Option<usize>,
    /// Offset for pagination
    pub offset: Option<usize>,
}

// ============================================================================
// Scan Types
// ============================================================================

/// Type of scan to perform
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ScanType {
    /// Quick scan - critical areas only
    Quick,
    /// Full system scan
    Full,
    /// Custom scan with specific paths
    Custom,
    /// Memory scan
    Memory,
    /// Network scan
    Network,
    /// Registry scan (Windows only)
    Registry,
}

impl Default for ScanType {
    fn default() -> Self {
        Self::Quick
    }
}

/// Status of a scan operation
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ScanStatus {
    /// Scan is pending
    Pending,
    /// Scan is in progress
    Running,
    /// Scan completed successfully
    Completed,
    /// Scan was cancelled
    Cancelled,
    /// Scan failed with error
    Failed,
}

impl Default for ScanStatus {
    fn default() -> Self {
        Self::Pending
    }
}

/// Result of a scan operation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScanResult {
    /// Unique scan ID
    pub id: Uuid,
    /// Type of scan performed
    pub scan_type: ScanType,
    /// Current status
    pub status: ScanStatus,
    /// Progress percentage (0-100)
    pub progress: u8,
    /// Number of files scanned
    pub files_scanned: u64,
    /// Number of threats found
    pub threats_found: u32,
    /// Number of items quarantined
    pub items_quarantined: u32,
    /// List of detected threats
    pub threats: Vec<ThreatInfo>,
    /// Scan start time
    pub started_at: DateTime<Utc>,
    /// Scan end time (if completed)
    pub completed_at: Option<DateTime<Utc>>,
    /// Error message (if failed)
    pub error: Option<String>,
    /// Custom paths (for custom scans)
    pub custom_paths: Vec<String>,
}

impl ScanResult {
    /// Create a new scan result
    pub fn new(scan_type: ScanType) -> Self {
        Self {
            id: Uuid::new_v4(),
            scan_type,
            status: ScanStatus::Pending,
            progress: 0,
            files_scanned: 0,
            threats_found: 0,
            items_quarantined: 0,
            threats: Vec::new(),
            started_at: Utc::now(),
            completed_at: None,
            error: None,
            custom_paths: Vec::new(),
        }
    }
}

/// Information about a detected threat
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreatInfo {
    /// Threat name/identifier
    pub name: String,
    /// Detection method (YARA rule, ML model, etc.)
    pub detection_method: String,
    /// Affected file path
    pub file_path: String,
    /// Threat severity
    pub severity: AlertSeverity,
    /// Whether the threat was quarantined
    pub quarantined: bool,
    /// SHA256 hash of the file
    pub file_hash: Option<String>,
    /// Detection timestamp
    pub detected_at: DateTime<Utc>,
}

// ============================================================================
// System Metrics
// ============================================================================

/// System metrics collected from the agent
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemMetrics {
    /// CPU usage percentage (0-100)
    pub cpu_usage: f32,
    /// Memory usage in bytes
    pub memory_used: u64,
    /// Total memory in bytes
    pub memory_total: u64,
    /// Disk usage in bytes
    pub disk_used: u64,
    /// Total disk in bytes
    pub disk_total: u64,
    /// Network bytes received
    pub network_rx: u64,
    /// Network bytes sent
    pub network_tx: u64,
    /// Number of running processes
    pub process_count: u32,
    /// Number of active network connections
    pub connection_count: u32,
    /// System uptime in seconds
    pub uptime_seconds: u64,
    /// Timestamp of metrics collection
    pub timestamp: DateTime<Utc>,
}

impl Default for SystemMetrics {
    fn default() -> Self {
        Self {
            cpu_usage: 0.0,
            memory_used: 0,
            memory_total: 0,
            disk_used: 0,
            disk_total: 0,
            network_rx: 0,
            network_tx: 0,
            process_count: 0,
            connection_count: 0,
            uptime_seconds: 0,
            timestamp: Utc::now(),
        }
    }
}

// ============================================================================
// Event Notifications
// ============================================================================

/// Type of event notification
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum EventNotification {
    /// New alert generated
    Alert(Alert),
    /// Scan progress update
    ScanProgress {
        scan_id: Uuid,
        progress: u8,
        files_scanned: u64,
    },
    /// Scan completed
    ScanComplete(ScanResult),
    /// Agent status changed
    StatusChanged {
        agent_id: String,
        old_status: crate::AgentStatus,
        new_status: crate::AgentStatus,
    },
    /// System metrics update
    Metrics(SystemMetrics),
    /// Threat detected
    ThreatDetected {
        threat: ThreatInfo,
        auto_quarantined: bool,
    },
    /// Configuration updated
    ConfigUpdate {
        agent_id: String,
        config_version: u32,
    },
    /// Connection state changed
    ConnectionState {
        connected: bool,
        server_url: Option<String>,
    },
    /// Error occurred
    Error {
        code: String,
        message: String,
        details: Option<serde_json::Value>,
    },
}

// ============================================================================
// Error Types
// ============================================================================

/// Tamandua-specific errors for the GUI
#[derive(Debug, Clone, Serialize, Deserialize, thiserror::Error)]
pub enum TamanduaError {
    /// Connection error
    #[error("Connection error: {message}")]
    Connection {
        message: String,
        code: Option<String>,
    },

    /// Authentication error
    #[error("Authentication error: {message}")]
    Auth { message: String },

    /// Scan error
    #[error("Scan error: {message}")]
    Scan {
        scan_id: Option<Uuid>,
        message: String,
    },

    /// Configuration error
    #[error("Configuration error: {message}")]
    Config {
        message: String,
        field: Option<String>,
    },

    /// Agent error
    #[error("Agent error: {message}")]
    Agent {
        agent_id: Option<String>,
        message: String,
    },

    /// Internal error
    #[error("Internal error: {message}")]
    Internal { message: String },

    /// Permission denied
    #[error("Permission denied: {message}")]
    PermissionDenied {
        message: String,
        required_permission: Option<String>,
    },

    /// Resource not found
    #[error("Not found: {resource}")]
    NotFound { resource: String },

    /// Rate limited
    #[error("Rate limited: retry after {retry_after_ms}ms")]
    RateLimited { retry_after_ms: u64 },

    /// Timeout
    #[error("Operation timed out after {timeout_ms}ms")]
    Timeout { timeout_ms: u64, operation: String },

    /// IPC communication error
    #[error("IPC error: {0}")]
    IpcError(String),

    /// Agent disconnected
    #[error("Agent disconnected")]
    AgentDisconnected,

    /// Operation failed
    #[error("Operation failed: {0}")]
    OperationFailed(String),
}

impl TamanduaError {
    /// Create a connection error
    pub fn connection(message: impl Into<String>) -> Self {
        Self::Connection {
            message: message.into(),
            code: None,
        }
    }

    /// Create an authentication error
    pub fn auth(message: impl Into<String>) -> Self {
        Self::Auth {
            message: message.into(),
        }
    }

    /// Create a scan error
    pub fn scan(message: impl Into<String>) -> Self {
        Self::Scan {
            scan_id: None,
            message: message.into(),
        }
    }

    /// Create an internal error
    pub fn internal(message: impl Into<String>) -> Self {
        Self::Internal {
            message: message.into(),
        }
    }
}
